<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Annie Chen, Helen Hao, Jiabao Ye">

<title>Cards, Credit, and Churn - Discovering Behavioral and Demographic Factors Across the Credit Cards</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="36315 Final Project_files/libs/clipboard/clipboard.min.js"></script>
<script src="36315 Final Project_files/libs/quarto-html/quarto.js"></script>
<script src="36315 Final Project_files/libs/quarto-html/popper.min.js"></script>
<script src="36315 Final Project_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="36315 Final Project_files/libs/quarto-html/anchor.min.js"></script>
<link href="36315 Final Project_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="36315 Final Project_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="36315 Final Project_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="36315 Final Project_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="36315 Final Project_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cards, Credit, and Churn - Discovering Behavioral and Demographic Factors Across the Credit Cards</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Annie Chen, Helen Hao, Jiabao Ye </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Understanding the behaviors and demographic features of credit card users is crucial for banks aiming to lower their customer churn rates. By examining patterns across categorical and quantitative data, we uncover insights into customer profiles and investigate the factors affecting attrition. Our analysis will guide the bank in refining services, developing targeted marketing strategies, and ultimately improving customer retention.</p>
</section>
<section id="data-description" class="level2">
<h2 class="anchored" data-anchor-id="data-description">Data Description</h2>
<p>The dataset is from <a href="https://www.kaggle.com/datasets/sakshigoyal7/credit-card-customers">kaggle</a>’s Credit Card customers. It mainly describes the credit card customers’ behaviors and consists of 10,000 customers with their age, income, marital status, credit card limit, amount of transactions, etc. There are 21 features included:</p>
<ul>
<li><p>Clientnum: Client number. Unique identifier for the customer holding the account</p></li>
<li><p>Attrition_Flag: If the account is closed then 1 else 0</p></li>
<li><p>Customer_Age: Customer’s Age in Years</p></li>
<li><p>Gender: M=Male, F=Female</p></li>
<li><p>Dependent_count: Number of dependents</p></li>
<li><p>Education_Level: Educational Qualification of the account holder (example: high school, college graduate, etc.)</p></li>
<li><p>Marital_Status: Married, Single, Divorced, Unknown</p></li>
<li><p>Income_Category: Annual Income Category of the account holder (&lt; $40K, $40K - 60K, $60K - $80K, $80K-$120K, &gt; $120K, Unknown)</p></li>
<li><p>Card_Category: Type of Card (Blue, Silver, Gold, Platinum)</p></li>
<li><p>Months_on_book: Period of relationship with bank</p></li>
<li><p>Total_Relationship_Count: Total number of products held by the customer</p></li>
<li><p>Months_Inactive_12_mon: Number of months inactive in the last 12 months</p></li>
<li><p>Contacts_Count_12_mon: Number of Contacts in the last 12 months</p></li>
<li><p>Credit_Limit: Credit Limit on the Credit Card</p></li>
<li><p>Total_Revolving_Bal: Total Revolving Balance on the Credit Card</p></li>
<li><p>Avg_Open_To_Buy: Open-to-Buy Credit Line (Average of last 12 months)</p></li>
<li><p>Total_Amt_Chng_Q4_Q1: Change in Transaction Amount (Q4 over Q1)</p></li>
<li><p>Total_Trans_Amt: Total Transaction Amount (Last 12 months)</p></li>
<li><p>Total_Trans_Ct: Total Transaction Count (Last 12 months)</p></li>
<li><p>Total_Ct_Chng_Q4_Q1: Change in Transaction Count (Q4 over Q1)</p></li>
<li><p>Avg_Utilization_Ratio: Average Card Utilization Ratio&nbsp;</p></li>
</ul>
<p>Our study specifically focuses on below variables:</p>
<p>Demographics variables: Gender, Marital_Status, and Income_Category</p>
<p>Financial variables: Total_Revolving_Bal, Card Categories, Credit_Limit, Avg_Utilization_Ratio, Total_Trans_Amt, Total_Trans_Ct, and Attrition_Flag</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions:</h2>
<p>Throughout the report, we are going to investigate three research questions:</p>
<p>1. What demographic and behavioral factors are associated with different card categories?</p>
<p>2. How do behavioral patterns influence credit card limits?</p>
<p>3. Can Customer Behavioral Profiles Be Clustered to Reveal Distinct Attrition Risk Segments?</p>
</section>
<section id="question-1what-demographic-and-behavioral-factors-are-associated-with-different-card-categories" class="level2">
<h2 class="anchored" data-anchor-id="question-1what-demographic-and-behavioral-factors-are-associated-with-different-card-categories">Question 1：What demographic and behavioral factors are associated with different card categories?</h2>
<p>We are curious about how demographic and behavioral factors, such as total revolving balance and income category, are related to the credit card categories. We then decided to use a box plot, which can clearly show the distribution, median, and variability of balances across groups. Visualizing all three variables simultaneously enables a quick comparison of spending behavior across card types within each income bracket.</p>
<p><strong>1.1 Boxplot</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot highlights how credit behavior (as measured by revolving balance) varies not just by income, but also by the type of card held, which often corresponds to customer value or loyalty tier. From the boxplot, we observe that Gold and Platinum cardholders tend to have higher median revolving balances across several income levels, especially in the $60K-$80K and $120K+ ranges. Also, people with higher income tend to have higher revolving balances, especially for Platinum cards, which is indicated by narrower IQRs and higher medians around 1600 dollars. Interestingly, Blue and Silver cardholders maintain lower or more varied balances regardless of income, suggesting that card tier is not solely determined by income but may also reflect spending habits or credit utilization behavior.</p>
<p><strong>1.2 Mosaic Plot</strong></p>
<p>Other than the total revolving balance and income category, we want to investigate how different marital statuses are associated with different card categories. Here, we decided to use the mosaic plot since it can show the proportion of individuals in each group and the statistical significance of deviations from expected values. The color shading highlights whether the associations are stronger or weaker than expected, which allows easy identification of patterns.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This mosaic plot shows that single people are significantly overrepresented in the Silver card category, indicated by the strong blue shading. This suggests that a higher-than-expected number of singles hold Silver cards. Conversely, married individuals are underrepresented in the Silver card category, as shown by the red shading. This means that fewer married people hold Silver cards than expected. Singles are often earlier in their financial journey, with moderate income and spending needs that align with mid-tier cards. In contrast, married individuals typically have higher combined incomes and larger financial responsibilities, making them more likely to choose higher-tier cards with better rewards, leading to their underrepresentation in the Silver category. Other card categories (Blue, Gold, and Platinum) do not show strong color shading across marital statuses, implying that distributions there more closely follow expected values. The plot also shows that divorced and unknown marital status groups have relatively small representation across all card types.</p>
<p>Based on the results of the graphs above, we can conclude that higher median revolving balances are associated with superior card categories. Also, singles are significantly overrepresented in the Silver card category, while married individuals are underrepresented. To better understand how customers with different credit card categories actually behave financially, we proceed to research how behavioral patterns affect credit card limits.</p>
</section>
<section id="question-2how-do-behavioral-patterns-influence-credit-card-limits" class="level2">
<h2 class="anchored" data-anchor-id="question-2how-do-behavioral-patterns-influence-credit-card-limits">Question 2：How do behavioral patterns influence credit card limits?</h2>
<p>For this part, we would like to focus on credit limits and the relationship between them and some key variables, such as card categories (Blue, Silver, Gold, Platinum), average utilization ratios (0-1 scale), and demographic information including gender. This data allows us to examine relationships between credit access, product offerings, and customer behavior.</p>
<p><strong>2.1 Histogram</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The histogram of the credit limit shows that the distribution is heavily right-skewed, with the majority of customers having lower credit limits. The highest frequency occurs in the range above $2,000, where approximately 2,200 customers are represented. The second highest frequency is around $4,000, with about 1,500 customers. As credit limits increase, the number of customers decreases substantially, creating a long tail to the right. There are only a small number of customers with credit limits between $15,000 and $30,000. Moreover, there is a noticeable spike at around $34,000, indicating a small but significant group of customers with very high credit limits compared to the rest of the population. This type of distribution is common in financial data, where most customers have modest credit limits while a smaller segment qualifies for much higher limits based on factors like income, credit history, and financial stability.</p>
<p><strong>2.2 Ridgeline Plot</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This ridgeline plot shows the credit limit distribution for four different card types by following the sequence of Blue, Silver, Gold, and Platinum from bottom to top. Each card category has its distinct distribution pattern: Blue cards have their highest concentration at very low credit limits around $3,000, with a strong right-skewed distribution while there is a tiny bump near the $35,000 mark. Silver cards have a bimodal pattern with a substantial peak around $13,000, a dip, and then their highest peak at approximately $35,000. Gold cards show a multimodal distribution with three main peaks: a small one around $16,000, another smaller one around $23,000, and the most significant peak at approximately $35,000. Platinum cards have two peaks similar to gold cards, one around $16,000 and a much larger one at approximately $35,000. The visualization reveals that higher-tier card categories (Silver, Gold, Platinum) tend to have concentrations of credit limits in the higher ranges, particularly around $35,000, while the Blue category is predominantly associated with much lower credit limits. This suggests a clear stratification of credit limit offerings based on card category, with premium categories receiving substantially higher limits. This visualization confirms that card categories serve as effective proxies for creditworthiness, with issuers systematically offering higher limits to premium cardholders.</p>
<p><strong>2.3 Scatterplot</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The scatterplot shows a negative relationship between credit limits and average utilization ratio (0-1 scale). The average utilization ratio is calculated by using the amount of revolving credit used divided by the total credit available. The regression lines show that as the average utilization ratio increases, credit limits decline, especially for male customers, as the slope for the blue line is steeper. In the scatterplot, each dot represents a customer and the points are densely clustered at lower utilization ratios (left side of the plot), suggesting most customers use less than 50% of their credit. Outliers with very high utilization (near 1.0) are rare but show significantly lower credit limits. The gender gap is striking at the low average utilization ratio, when it is close to zero, men receive around $17,000 in credit, while women receive around $7,000. At high utilization levels, men’s trend line even decreases below zero, indicating steep limit reductions, while women’s levels flatten out. This suggests both behavioral risk and potential gender bias in credit allocation. The data highlights how financial behavior influences credit access, and how banks may respond differently to men and women.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Credit_Limit ~ Avg_Utilization_Ratio * Gender, data = credit_card)

Residuals:
     Min       1Q   Median       3Q      Max 
-16208.0  -3865.7   -779.6   1642.8  27684.9 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     7321.6      148.7   49.23   &lt;2e-16 ***
Avg_Utilization_Ratio          -6719.5      330.1  -20.36   &lt;2e-16 ***
GenderM                        10324.7      201.0   51.36   &lt;2e-16 ***
Avg_Utilization_Ratio:GenderM -18139.9      551.3  -32.91   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 7086 on 10123 degrees of freedom
Multiple R-squared:  0.3923,    Adjusted R-squared:  0.3921 
F-statistic:  2178 on 3 and 10123 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>To back up the above scatterplot, a regression analysis is provided. The model tests the interaction between the average utilization ratio and gender on credit limits. Females with 0 utilization have an average credit limit of $7321.6 and each 1 unit increase in utilization ratio (average utilization ratio rises from 0 to 1) will reduce females’ credit limit by $6719.5. In that case, when the female’s average utilization increases by 0.1, the credit limit will decrease by $671.95. Males start with $10,324.7 higher credit limits than females at 0 average utilization ratio, which is $17646.3. Moreover, males’ credit limits drop $18139.9 more per unit of utilization than females, which means as male average utilization increases by 0.1, the credit limit will decrease by $2485.94. All coefficients have p-values &lt; 2e-16, indicating the statistical significance. The interaction term confirms that the relationship between utilization and credit limit differs significantly by gender. The regression model explains 39.23% of credit limit variance (R² = 0.3923), indicating utilization behavior and gender are substantial but not exclusive determinants of credit access.</p>
<p>The analysis reveals three key insights about credit limits, firstly, most customers receive modest limits (&lt;$15k), with exponential decay in higher limits. Secondly, card categories effectively segment customers by creditworthiness, with premium cards receiving higher limits. Last but not least, the utilization behavior significantly impacts limits, with notable gender-based differences. These findings suggest that credit issuers rely on a combination of product segmentation, financial behavior, and demographic factors when determining limits, patterns that may also shape broader customer retention risks explored in our third research question.</p>
</section>
<section id="question-3-can-customer-behavioral-profiles-be-clustered-to-reveal-distinct-attrition-risk-segments" class="level2">
<h2 class="anchored" data-anchor-id="question-3-can-customer-behavioral-profiles-be-clustered-to-reveal-distinct-attrition-risk-segments">Question 3: Can Customer Behavioral Profiles Be Clustered to Reveal Distinct Attrition Risk Segments?</h2>
<p>While exploring the dataset, we became particularly interested in customer attrition patterns and whether behavioral profiles could be used to cluster customers into distinct risk segments, motivating our third research question.</p>
<p><strong>3.1 Bar Chart</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart shows that about 16.1% of customers in our dataset have attrited, while 83.9% remained. Although the attrited group is the minority, its financial impact can still be significant because every lost customer carries both a hard cost (acquisition investment) and a lost future revenue stream. In high-volume retail banking, small shifts in churn can translate into millions of dollars in lost value annually.&nbsp;</p>
<p><strong>3.2 Heatmap</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To justify the use of PCA, we generated a correlation heatmap using standardized numeric behavioral variables. The heatmap revealed several strong correlations, for example: the correlation between Total_Trans_Amt and Total_Trans_Ct is 0.81 and the correlation between Credit_Limit and Avg_Open_To_Buy is 1.00, showing a perfect correlation. These relationships suggest redundancy in the dataset. High correlation indicates shared variance, which PCA can compress into fewer orthogonal dimensions. At the same time, a perfect correlation between variables like Credit_Limit and Avg_Open_To_Buy poses a problem for PCA, as it violates assumptions of linear independence and results in a singular covariance matrix. Thus, Avg_Open_To_Buy was removed to preserve numerical stability. Overall, the heatmap supports the application of PCA as a dimensionality reduction technique.</p>
<p><strong>3.3 Scree Plot</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To perform PCA, according to the correlation heatmap, we decided to include the following variables: Total_Trans_Amt, Total_Trans_Ct, Total_Amt_Chng_Q4_Q1, Total_Ct_Chng_Q4_Q1, Credit_Limit, Contacts_Count_12_mon, Months_Inactive_12_mon, and Total_Relationship_Count. Those variables were chosen due to their behavioral relevance and moderate-to-strong correlations, which are suitable for dimensionality reduction. On the other hand, variables such as Avg_Open_To_Buy, Dependent_count, and Customer_Age were excluded either due to perfect correlation (in the case of Avg_Open_To_Buy) or weaker relevance to recent engagement behavior. The scree plot shows that the first two principal components explain approximately 43.5% of the total variance. PC1 and PC2’s results demonstrate that PCA successfully identifies underlying behavioral factors: the first component reflects general activity level, while the second captures recent changes in behavior. The huge decrease in explained variance after the second component also justifies using a 2D PCA representation.</p>
<p><strong>3.4 Biplot</strong></p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="36315-Final-Project_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We then create a PCA biplot that visually segments customers in the new PCA space, where each point represents a customer projected into the 2D space of PC1 and PC2, and directional arrows indicate the contribution of original features to each principal component. We found that the biplot reveals a clear separation between attrited and existing customers: attrited customers cluster on the negative side of PC1 and PC2, suggesting low transaction activity, low momentum, and higher inactivity. Existing customers cluster on the positive side of both dimensions, aligned with high transaction count, high amount, and increasing behavioral trends. The visual evidence supports the idea that PCA effectively encodes meaningful behavior differences and that these dimensions are predictive of attrition risk.</p>
<p>Our PCA analysis did a great job of dimensionality reduction and exploratory visualization: We overlaid known churn labels to demonstrate separation. However, PCA alone was not an unsupervised clustering algorithm. To formally segment customers, we would apply K-means to the PC scores and evaluate cluster validity and attrition purity in future work.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>This study provides a comprehensive exploration of how demographic factors, behavioral patterns, and financial engagement relate to credit card usage and customer attrition. We find that premium cardholders, particularly those holding Gold and Platinum cards, tend to have higher revolving balances and are often concentrated within higher income brackets, though spending behavior also plays an important role independent of income. Marital status significantly influences card selection, with single individuals being overrepresented among Silver cardholders while married customers are less represented in this category.&nbsp;</p>
<p>Our analysis of credit limits reveals a heavily right-skewed distribution, where most customers are assigned modest limits under $15,000, while a smaller group enjoys substantially higher limits near $35,000. &nbsp;The card categories effectively segment customers by creditworthiness, with premium cards receiving higher limits. We also identify notable gender disparities as male customers generally receive higher baseline credit limits but face steeper penalties for higher utilization ratios.&nbsp;</p>
<p>Finally, we care about what factors cause customer retention as we discovered that 16.1% of customers had left, which is a minority, but one with real financial impact. After noticing substantial redundancy among behavioral variables, we ran a PCA that revealed two key dimensions explaining 43.5% of behavioral variance: overall activity level and recent engagement trends. These findings suggest that demographic factors, financial behaviors, and product segmentation jointly influence not only customer experience but also long-term retention outcomes.</p>
</section>
<section id="recommendations" class="level2">
<h2 class="anchored" data-anchor-id="recommendations">Recommendations</h2>
<p>Based on our research questions and findings, we recommend three key strategic actions for the banks:</p>
<p>1. Optimize Card Category Offerings&nbsp;</p>
<p>According to our research findings regarding the demographic and behavioral factors associated with different card categories, the bank should refine its card offerings to fulfill the identified customer segments. Premium cards should be marketed more aggressively to high-income brackets where revolving balances tend to be higher, while Blue and Silver card benefits should be redesigned to encourage greater engagement from these more varied customer segments. Creating clearer value propositions for each card tier would strengthen customer identification with their product and reduce the likelihood of seeking alternatives elsewhere.&nbsp;</p>
<p>2. Reform Credit Limit Allocation Strategies</p>
<p>Our credit limit analysis revealed concerning patterns in limit allocation, particularly regarding gender disparities and utilization penalties. The bank should implement a more transparent and equitable credit limit system that reduces the observed gap between male and female customers at lower utilization levels. Additionally, the significant right-skewed distribution of credit limits suggests an opportunity to create more intermediate tiers between the most common limits and the highest limits, potentially increasing engagement among customers who feel their current limit is inadequate but don’t qualify for the highest tier.</p>
<p>3. Develop a Predictive Attrition Intervention System</p>
<p>We found a clear separation between existing and attrited customers revealed by our PCA analysis, which provides a strong foundation for a predictive intervention system. The bank should implement automated monitoring for the key behavioral indicators identified in our study: declining transaction frequency, increasing inactivity periods, and reduced transaction growth. When these warning signs appear, targeted retention initiatives should be triggered before the customer decides to leave. We believe this approach would allow the bank to focus retention resources on the customers most likely to attrite while also addressing the specific pain points that typically lead to customer departure.</p>
</section>
<section id="future-study" class="level2">
<h2 class="anchored" data-anchor-id="future-study">Future study</h2>
<p>While our study identifies clear associations between customer profiles, card usage patterns, and attrition risks, several opportunities remain for extending this research. Future studies should expand the range of variables considered by incorporating additional demographic information such as education levels, occupations, or household sizes. This would provide a more detailed understanding of customer segments and better capture factors influencing financial behavior.</p>
<p>Moreover, including financial metrics such as credit scores or loan history could improve predictive modeling and allow for a more comprehensive analysis of creditworthiness and retention risks. Expanding both the depth of variables and the sophistication of modeling techniques would enhance the bank’s ability to design more personalized, effective customer management strategies. Finally, we would apply machine learning clustering algorithms like K-Means to the PCA scores to formally segment customers based on their behavioral profiles.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>